#!/bin/bash
set -e

CONFIG_FILE="/var/www/html/qa-config.php"

# ============================================
# Generate qa-config.php from environment vars
# ============================================

if [ -n "$QA_MYSQL_HOSTNAME" ]; then
  echo "[Q2A] Generating qa-config.php from environment variables..."

  php -r "
    \$config = '<?php' . PHP_EOL;
    \$config .= '/*' . PHP_EOL;
    \$config .= '  Question2Answer configuration — auto-generated by Docker entrypoint.' . PHP_EOL;
    \$config .= '  https://github.com/dublyo/question2answer' . PHP_EOL;
    \$config .= '*/' . PHP_EOL . PHP_EOL;

    // Required MySQL settings
    \$config .= \"  define('QA_MYSQL_HOSTNAME', \" . var_export(getenv('QA_MYSQL_HOSTNAME'), true) . \");\" . PHP_EOL;
    \$config .= \"  define('QA_MYSQL_USERNAME', \" . var_export(getenv('QA_MYSQL_USERNAME'), true) . \");\" . PHP_EOL;
    \$config .= \"  define('QA_MYSQL_PASSWORD', \" . var_export(getenv('QA_MYSQL_PASSWORD'), true) . \");\" . PHP_EOL;
    \$config .= \"  define('QA_MYSQL_DATABASE', \" . var_export(getenv('QA_MYSQL_DATABASE'), true) . \");\" . PHP_EOL;

    // Optional MySQL port
    \$port = getenv('QA_MYSQL_PORT');
    if (\$port) {
      \$config .= \"  define('QA_MYSQL_PORT', \" . var_export(\$port, true) . \");\" . PHP_EOL;
    }

    // Table prefix
    \$prefix = getenv('QA_MYSQL_TABLE_PREFIX') ?: 'qa_';
    \$config .= \"  define('QA_MYSQL_TABLE_PREFIX', \" . var_export(\$prefix, true) . \");\" . PHP_EOL;

    \$config .= \"  define('QA_EXTERNAL_USERS', false);\" . PHP_EOL;
    \$config .= \"  define('QA_BLOBS_DIRECTORY', '/var/www/html/qa-blobs/');\" . PHP_EOL;
    \$config .= \"  define('QA_CACHE_DIRECTORY', '/var/www/html/qa-cache/');\" . PHP_EOL;

    // Performance — optimized for Docker (DB in separate container)
    \$config .= \"  define('QA_HTML_COMPRESSION', true);\" . PHP_EOL;
    \$config .= \"  define('QA_MAX_LIMIT_START', 19999);\" . PHP_EOL;
    \$config .= \"  define('QA_IGNORED_WORDS_FREQ', 10000);\" . PHP_EOL;
    \$config .= \"  define('QA_ALLOW_UNINDEXED_QUERIES', false);\" . PHP_EOL;
    \$config .= \"  define('QA_OPTIMIZE_DISTANT_DB', true);\" . PHP_EOL;
    \$config .= \"  define('QA_PERSISTENT_CONN_DB', false);\" . PHP_EOL;
    \$config .= \"  define('QA_DEBUG_PERFORMANCE', false);\" . PHP_EOL;

    file_put_contents('$CONFIG_FILE', \$config);
  "

  chown www-data:www-data "$CONFIG_FILE"
  chmod 640 "$CONFIG_FILE"

  echo "[Q2A] qa-config.php created successfully"
else
  if [ ! -f "$CONFIG_FILE" ]; then
    echo "[Q2A] WARNING: No QA_MYSQL_HOSTNAME set and no qa-config.php found."
    echo "[Q2A] Copy qa-config-example.php to qa-config.php and configure manually."
  fi
fi

# ============================================
# Fix permissions on writable directories
# ============================================
chown -R www-data:www-data /var/www/html/qa-cache /var/www/html/qa-content
[ -d /var/www/html/qa-blobs ] && chown -R www-data:www-data /var/www/html/qa-blobs

# ============================================
# Wait for MySQL to be ready
# ============================================
if [ -n "$QA_MYSQL_HOSTNAME" ]; then
  echo "[Q2A] Waiting for MySQL at ${QA_MYSQL_HOSTNAME}..."

  MAX_TRIES=30
  COUNT=0
  until php -r "
    \$c = @new mysqli(getenv('QA_MYSQL_HOSTNAME'), getenv('QA_MYSQL_USERNAME'), getenv('QA_MYSQL_PASSWORD'), getenv('QA_MYSQL_DATABASE'), (int)(getenv('QA_MYSQL_PORT') ?: 3306));
    if (\$c->connect_errno) exit(1);
    \$c->close();
  " 2>/dev/null; do
    COUNT=$((COUNT + 1))
    if [ $COUNT -ge $MAX_TRIES ]; then
      echo "[Q2A] WARNING: MySQL not ready after ${MAX_TRIES} attempts, starting anyway..."
      break
    fi
    echo "[Q2A] MySQL not ready yet (attempt ${COUNT}/${MAX_TRIES})..."
    sleep 2
  done

  if [ $COUNT -lt $MAX_TRIES ]; then
    echo "[Q2A] MySQL connection OK"
  fi
fi

echo "[Q2A] Starting Apache..."
exec "$@"
